// buat nyimpen semua nama berkas yang dibutuhin buat masing" skema
export const SECTIONS = {
  WAJIB: 'WAJIB',
  JURNAL: 'Publikasi Jurnal',
  PROCEEDING: 'Proceeding International',
  HKI: 'HKI'
};

export const DOCUMENT_CONFIG = {
  [SECTIONS.WAJIB]: [
    'BERKAS FORM VALIDASI DOSEN WALI',
    'BERKAS REKOMENDASI SIDANG PEMBIMBIMB',
    'BERKAS SCAN PERNYATAAN BIODATA IJAZAH BERMATERAI',
    'BERKAS DUMMY IJAZAH BERMATERAI',
    'BERKAS SCAN SCAN AKTA KELAHIRAN',
    'BERKAS SCAN IJAZAH TERAKHIR',
    'BERKAS SCAN KHS DENGAN TTD DOSWAL/KAPRODI',
    'BERKAS LOG BIMBINGAN',
    'BERKAS PEMAKLUMAN TEST BAHASA(OPSIONAL)',
    'BERKAS SERTIFIKAT TAK',
    'BERKAS REKOMENDASI BERKAS EVIDENCE TA/PA IGRACIAS PEMBIMBING',
    'UPLOAD DRAFT BUKU TA SIAP SIDANG'
  ],
  [SECTIONS.JURNAL]: [
    'BERKAS LoA',
    'BERKAS PERSETUJUAN PUBLIKASI TA SEBAGAI PENGGANTI SIDANG',
    'BERKAS CAMERA READY PAPER (YANG SUDAH TERBIT)',
    'BERKAS CAMERA READY PAPER',
    'BERKAS RIWAYAT RIVIEW OLEH REVIEWERS',
    'BERKAS RESPONSE'
  ],
  [SECTIONS.PROCEEDING]: [
    'BERKAS LoA',
    'BERKAS PERSETUJUAN PUBLIKASI TA SEBAGAI PENGGANTI SIDANG',
    'BERKAS CAMERA READY PAPER',
    'BERKAS PAKTA INTEGRITAS',
    'BERKAS RESPONSE'
  ],
  [SECTIONS.HKI]: [
    'SERTIFIKAT HKI',
    'SERTIFIKAT DARI MITRA DUDI',
    'SERTIFIKAT PENDUKUNG LAINNYA'
  ]
};

// Map display names to keys used in data.jalurNonSidang
export const PATH_MAP = {
  'Publikasi Jurnal': SECTIONS.JURNAL,
  'Proceeding International': SECTIONS.PROCEEDING,
  'HKI': SECTIONS.HKI
};
