import express from 'express';
import authRouter from './auth.js';
import adminRouter from './admin.js';
import researchGroupRouter from './researchGroup.js';
import dosenRouter from './dosen.js';
import facultyRouter from './faculty.js';
import studyProgramRouter from './studyProgram.js';
import mahasiswaRouter from './mahasiswa.js';
import permohonanSktaRouter from './permohonanSkta.js';
import templateRouter from './templateUpload.js';
import sidangPeriodRouter from './sidangPeriod.js';
import sidangRegistrationPeriodRouter from './sidangRegsitrationPeriod.js';
import sidangRegistrationRouter from './sidangRegistration.js';
import sidangRegistrationResponseRouter from './sidangRegistrationResponse.js';
import yudisiumPeriodRouter from './yudisiumPeriod.js';
import yudisiumRegistrationPeriodRouter from './yudisiumRegsitrationPeriod.js';
import yudisiumRegistrationRouter from './yudisiumRegistration.js';
import yudisiumRegistrationResponseRouter from './yudisiumRegistrationResponse.js';
import sklUploadRouter from './sklUpload.js';
import transkripUploadRouter from './transkripUpload.js';
import dokumenValidasiSktaUploadRouter from './dokumenValidasiSktaUpload.js';
import formulirPenerbitanSktaUploadRouter from './formulirPenerbitanSktaUpload.js';
import berkasMahasiswaRouter from './berkasMahasiswa.js';

const router = express.Router();

router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/research-groups", researchGroupRouter);
router.use("/dosen", dosenRouter);
router.use("/faculties", facultyRouter);
router.use("/study-programs", studyProgramRouter);
router.use("/mahasiswa", mahasiswaRouter);
router.use("/permohonan-skta", permohonanSktaRouter);
router.use("/templates", templateRouter);
router.use("/sidang-periods", sidangPeriodRouter);
router.use("/sidang-registration-periods", sidangRegistrationPeriodRouter);
router.use("/sidang-registrations", sidangRegistrationRouter);
router.use("/sidang-registration-responses", sidangRegistrationResponseRouter);
router.use("/yudisium-periods", yudisiumPeriodRouter);
router.use("/yudisium-registration-periods", yudisiumRegistrationPeriodRouter);
router.use("/yudisium-registrations", yudisiumRegistrationRouter);
router.use("/yudisium-registration-responses", yudisiumRegistrationResponseRouter);
router.use("/skl", sklUploadRouter);
router.use("/transkrip", transkripUploadRouter);
router.use("/dokumen-validasi-skta", dokumenValidasiSktaUploadRouter);
router.use("/formulir-penerbitan-skta", formulirPenerbitanSktaUploadRouter);
router.use("/berkas-mahasiswa", berkasMahasiswaRouter);

export default router;
