import express from 'express';
import authRouter from './auth.js';
import adminRouter from './admin.js';
import researchGroupRouter from './researchGroup.js';
import dosenRouter from './dosen.js';
import facultyRouter from './faculty.js';
import studyProgramRouter from './studyProgram.js';
import mahasiswaRouter from './mahasiswa.js';
import permohonanSktaRouter from './permohonanSkta.js';
import templateRouter from './templateUpload.js';
import pusatInformasiRouter from './pusatInformasi.js';
import sidangPeriodRouter from './sidangPeriod.js';
import sidangRegistrationRouter from './sidangRegistration.js';
import penjadwalanSidangRouter from './penjadwalanSidang.js';
import yudisiumPeriodRouter from './yudisiumPeriod.js';
import yudisiumRegistrationRouter from './yudisiumRegistration.js';
import sklUploadRouter from './sklUpload.js';
import transkripUploadRouter from './transkripUpload.js';
import ruanganRouter from './ruangan.js';
import mahasiswaBimbinganRouter from './mahasiswaBimbingan.js';
import healthRouter from './health.js';
import cloRouter from './clo.js';
import subcloRouter from './subclo.js';
import jenisAsesmenRouter from './jenisAsesmen.js';
import skemaPenilaiRouter from './skemaPenilai.js';

const router = express.Router();

router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/research-groups", researchGroupRouter);
router.use("/dosen", dosenRouter);
router.use("/mahasiswa-bimbingan", mahasiswaBimbinganRouter);
router.use("/faculties", facultyRouter);
router.use("/study-programs", studyProgramRouter);
router.use("/mahasiswa", mahasiswaRouter);
router.use("/permohonan-skta", permohonanSktaRouter);
router.use("/templates", templateRouter);
router.use("/pusat-informasi", pusatInformasiRouter);
router.use("/sidang-periods", sidangPeriodRouter);
router.use("/sidang-registrations", sidangRegistrationRouter);
router.use("/penjadwalan-sidang", penjadwalanSidangRouter);
router.use("/yudisium-periods", yudisiumPeriodRouter);
router.use("/yudisium-registrations", yudisiumRegistrationRouter);
router.use("/skl", sklUploadRouter);
router.use("/transkrip", transkripUploadRouter);
router.use("/ruangan", ruanganRouter);
router.use("/clo", cloRouter);
router.use("/subclo", subcloRouter);
router.use("/jenis-asesmen", jenisAsesmenRouter);
router.use("/skema-penilai", skemaPenilaiRouter);

export default router;
